<?php
return [
    'devices' => [
        'desktop' => 'Desktop',
        'mobile' => 'Mobile',
        'tablet' => 'Tablet'
    ],
    'pays' => [
        'AF' => ['nom' => 'Afghanistan', 'flag' => 'af'],
        'AX' => ['nom' => 'Åland Islands', 'flag' => 'ax'],
        'AL' => ['nom' => 'Albania', 'flag' => 'al'],
        'DZ' => ['nom' => 'Algeria', 'flag' => 'dz'],
        'AS' => ['nom' => 'American Samoa', 'flag' => 'as'],
        'AD' => ['nom' => 'Andorra', 'flag' => 'ad'],
        'AO' => ['nom' => 'Angola', 'flag' => 'ao'],
        'AI' => ['nom' => 'Anguilla', 'flag' => 'ai'],
        'AQ' => ['nom' => 'Antarctica', 'flag' => 'aq'],
        'AG' => ['nom' => 'Antigua and Barbuda', 'flag' => 'ag'],
        'AR' => ['nom' => 'Argentina', 'flag' => 'ar'],
        'AM' => ['nom' => 'Armenia', 'flag' => 'am'],
        'AW' => ['nom' => 'Aruba', 'flag' => 'aw'],
        'AU' => ['nom' => 'Australia', 'flag' => 'au'],
        'AT' => ['nom' => 'Austria', 'flag' => 'at'],
        'AZ' => ['nom' => 'Azerbaijan', 'flag' => 'az'],
        'BS' => ['nom' => 'Bahamas', 'flag' => 'bs'],
        'BH' => ['nom' => 'Bahrain', 'flag' => 'bh'],
        'BD' => ['nom' => 'Bangladesh', 'flag' => 'bd'],
        'BB' => ['nom' => 'Barbados', 'flag' => 'bb'],
        'BY' => ['nom' => 'Belarus', 'flag' => 'by'],
        'BE' => ['nom' => 'Belgium', 'flag' => 'be'],
        'BZ' => ['nom' => 'Belize', 'flag' => 'bz'],
        'BJ' => ['nom' => 'Benin', 'flag' => 'bj'],
        'BM' => ['nom' => 'Bermuda', 'flag' => 'bm'],
        'BT' => ['nom' => 'Bhutan', 'flag' => 'bt'],
        'BO' => ['nom' => 'Bolivia', 'flag' => 'bo'],
        'BQ' => ['nom' => 'Bonaire, Sint Eustatius and Saba', 'flag' => 'bq'],
        'BA' => ['nom' => 'Bosnia and Herzegovina', 'flag' => 'ba'],
        'BW' => ['nom' => 'Botswana', 'flag' => 'bw'],
        'BV' => ['nom' => 'Bouvet Island', 'flag' => 'bv'],
        'BR' => ['nom' => 'Brazil', 'flag' => 'br'],
        'IO' => ['nom' => 'British Indian Ocean Territory', 'flag' => 'io'],
        'BN' => ['nom' => 'Brunei Darussalam', 'flag' => 'bn'],
        'BG' => ['nom' => 'Bulgaria', 'flag' => 'bg'],
        'BF' => ['nom' => 'Burkina Faso', 'flag' => 'bf'],
        'BI' => ['nom' => 'Burundi', 'flag' => 'bi'],
        'CV' => ['nom' => 'Cabo Verde', 'flag' => 'cv'],
        'KH' => ['nom' => 'Cambodia', 'flag' => 'kh'],
        'CM' => ['nom' => 'Cameroon', 'flag' => 'cm'],
        'CA' => ['nom' => 'Canada', 'flag' => 'ca'],
        'KY' => ['nom' => 'Cayman Islands', 'flag' => 'ky'],
        'CF' => ['nom' => 'Central African Republic', 'flag' => 'cf'],
        'TD' => ['nom' => 'Chad', 'flag' => 'td'],
        'CL' => ['nom' => 'Chile', 'flag' => 'cl'],
        'CN' => ['nom' => 'China', 'flag' => 'cn'],
        'CX' => ['nom' => 'Christmas Island', 'flag' => 'cx'],
        'CC' => ['nom' => 'Cocos (Keeling) Islands', 'flag' => 'cc'],
        'CO' => ['nom' => 'Colombia', 'flag' => 'co'],
        'KM' => ['nom' => 'Comoros', 'flag' => 'km'],
        'CD' => ['nom' => 'Congo (Democratic Republic)', 'flag' => 'cd'],
        'CG' => ['nom' => 'Congo', 'flag' => 'cg'],
        'CK' => ['nom' => 'Cook Islands', 'flag' => 'ck'],
        'CR' => ['nom' => 'Costa Rica', 'flag' => 'cr'],
        'CI' => ['nom' => 'Côte d\'Ivoire', 'flag' => 'ci'],
        'HR' => ['nom' => 'Croatia', 'flag' => 'hr'],
        'CU' => ['nom' => 'Cuba', 'flag' => 'cu'],
        'CW' => ['nom' => 'Curaçao', 'flag' => 'cw'],
        'CY' => ['nom' => 'Cyprus', 'flag' => 'cy'],
        'CZ' => ['nom' => 'Czech Republic', 'flag' => 'cz'],
        'DK' => ['nom' => 'Denmark', 'flag' => 'dk'],
        'DJ' => ['nom' => 'Djibouti', 'flag' => 'dj'],
        'DM' => ['nom' => 'Dominica', 'flag' => 'dm'],
        'DO' => ['nom' => 'Dominican Republic', 'flag' => 'do'],
        'EC' => ['nom' => 'Ecuador', 'flag' => 'ec'],
        'EG' => ['nom' => 'Egypt', 'flag' => 'eg'],
        'SV' => ['nom' => 'El Salvador', 'flag' => 'sv'],
        'GQ' => ['nom' => 'Equatorial Guinea', 'flag' => 'gq'],
        'ER' => ['nom' => 'Eritrea', 'flag' => 'er'],
        'EE' => ['nom' => 'Estonia', 'flag' => 'ee'],
        'SZ' => ['nom' => 'Eswatini', 'flag' => 'sz'],
        'ET' => ['nom' => 'Ethiopia', 'flag' => 'et'],
        'FK' => ['nom' => 'Falkland Islands (Malvinas)', 'flag' => 'fk'],
        'FO' => ['nom' => 'Faroe Islands', 'flag' => 'fo'],
        'FJ' => ['nom' => 'Fiji', 'flag' => 'fj'],
        'FI' => ['nom' => 'Finland', 'flag' => 'fi'],
        'FR' => ['nom' => 'France', 'flag' => 'fr'],
        'GF' => ['nom' => 'French Guiana', 'flag' => 'gf'],
        'PF' => ['nom' => 'French Polynesia', 'flag' => 'pf'],
        'TF' => ['nom' => 'French Southern Territories', 'flag' => 'tf'],
        'GA' => ['nom' => 'Gabon', 'flag' => 'ga'],
        'GM' => ['nom' => 'Gambia', 'flag' => 'gm'],
        'GE' => ['nom' => 'Georgia', 'flag' => 'ge'],
        'DE' => ['nom' => 'Germany', 'flag' => 'de'],
        'GH' => ['nom' => 'Ghana', 'flag' => 'gh'],
        'GI' => ['nom' => 'Gibraltar', 'flag' => 'gi'],
        'GR' => ['nom' => 'Greece', 'flag' => 'gr'],
        'GL' => ['nom' => 'Greenland', 'flag' => 'gl'],
        'GD' => ['nom' => 'Grenada', 'flag' => 'gd'],
        'GP' => ['nom' => 'Guadeloupe', 'flag' => 'gp'],
        'GU' => ['nom' => 'Guam', 'flag' => 'gu'],
        'GT' => ['nom' => 'Guatemala', 'flag' => 'gt'],
        'GG' => ['nom' => 'Guernsey', 'flag' => 'gg'],
        'GN' => ['nom' => 'Guinea', 'flag' => 'gn'],
        'GW' => ['nom' => 'Guinea-Bissau', 'flag' => 'gw'],
        'GY' => ['nom' => 'Guyana', 'flag' => 'gy'],
        'HT' => ['nom' => 'Haiti', 'flag' => 'ht'],
        'HM' => ['nom' => 'Heard Island and McDonald Islands', 'flag' => 'hm'],
        'VA' => ['nom' => 'Holy See (Vatican City State)', 'flag' => 'va'],
        'HN' => ['nom' => 'Honduras', 'flag' => 'hn'],
        'HK' => ['nom' => 'Hong Kong', 'flag' => 'hk'],
        'HU' => ['nom' => 'Hungary', 'flag' => 'hu'],
        'IS' => ['nom' => 'Iceland', 'flag' => 'is'],
        'IN' => ['nom' => 'India', 'flag' => 'in'],
        'ID' => ['nom' => 'Indonesia', 'flag' => 'id'],
        'IR' => ['nom' => 'Iran', 'flag' => 'ir'],
        'IQ' => ['nom' => 'Iraq', 'flag' => 'iq'],
        'IE' => ['nom' => 'Ireland', 'flag' => 'ie'],
        'IM' => ['nom' => 'Isle of Man', 'flag' => 'im'],
        'IL' => ['nom' => 'Israel', 'flag' => 'il'],
        'IT' => ['nom' => 'Italy', 'flag' => 'it'],
        'JM' => ['nom' => 'Jamaica', 'flag' => 'jm'],
        'JP' => ['nom' => 'Japan', 'flag' => 'jp'],
        'JE' => ['nom' => 'Jersey', 'flag' => 'je'],
        'JO' => ['nom' => 'Jordan', 'flag' => 'jo'],
        'KZ' => ['nom' => 'Kazakhstan', 'flag' => 'kz'],
        'KE' => ['nom' => 'Kenya', 'flag' => 'ke'],
        'KI' => ['nom' => 'Kiribati', 'flag' => 'ki'],
        'KP' => ['nom' => 'Korea (North)', 'flag' => 'kp'],
        'KR' => ['nom' => 'Korea (South)', 'flag' => 'kr'],
        'KW' => ['nom' => 'Kuwait', 'flag' => 'kw'],
        'KG' => ['nom' => 'Kyrgyzstan', 'flag' => 'kg'],
        'LA' => ['nom' => 'Lao People\'s Democratic Republic', 'flag' => 'la'],
        'LV' => ['nom' => 'Latvia', 'flag' => 'lv'],
        'LB' => ['nom' => 'Lebanon', 'flag' => 'lb'],
        'LS' => ['nom' => 'Lesotho', 'flag' => 'ls'],
        'LR' => ['nom' => 'Liberia', 'flag' => 'lr'],
        'LY' => ['nom' => 'Libya', 'flag' => 'ly'],
        'LI' => ['nom' => 'Liechtenstein', 'flag' => 'li'],
        'LT' => ['nom' => 'Lithuania', 'flag' => 'lt'],
        'LU' => ['nom' => 'Luxembourg', 'flag' => 'lu'],
        'MO' => ['nom' => 'Macao', 'flag' => 'mo'],
        'MK' => ['nom' => 'North Macedonia', 'flag' => 'mk'],
        'MG' => ['nom' => 'Madagascar', 'flag' => 'mg'],
        'MW' => ['nom' => 'Malawi', 'flag' => 'mw'],
        'MY' => ['nom' => 'Malaysia', 'flag' => 'my'],
        'MV' => ['nom' => 'Maldives', 'flag' => 'mv'],
        'ML' => ['nom' => 'Mali', 'flag' => 'ml'],
        'MT' => ['nom' => 'Malta', 'flag' => 'mt'],
        'MH' => ['nom' => 'Marshall Islands', 'flag' => 'mh'],
        'MQ' => ['nom' => 'Martinique', 'flag' => 'mq'],
        'MR' => ['nom' => 'Mauritania', 'flag' => 'mr'],
        'MU' => ['nom' => 'Mauritius', 'flag' => 'mu'],
        'YT' => ['nom' => 'Mayotte', 'flag' => 'yt'],
        'MX' => ['nom' => 'Mexico', 'flag' => 'mx'],
        'FM' => ['nom' => 'Micronesia', 'flag' => 'fm'],
        'MD' => ['nom' => 'Moldova', 'flag' => 'md'],
        'MC' => ['nom' => 'Monaco', 'flag' => 'mc'],
        'MN' => ['nom' => 'Mongolia', 'flag' => 'mn'],
        'ME' => ['nom' => 'Montenegro', 'flag' => 'me'],
        'MS' => ['nom' => 'Montserrat', 'flag' => 'ms'],
        'MA' => ['nom' => 'Morocco', 'flag' => 'ma'],
        'MZ' => ['nom' => 'Mozambique', 'flag' => 'mz'],
        'MM' => ['nom' => 'Myanmar', 'flag' => 'mm'],
        'NA' => ['nom' => 'Namibia', 'flag' => 'na'],
        'NR' => ['nom' => 'Nauru', 'flag' => 'nr'],
        'NP' => ['nom' => 'Nepal', 'flag' => 'np'],
        'NL' => ['nom' => 'Netherlands', 'flag' => 'nl'],
        'NC' => ['nom' => 'New Caledonia', 'flag' => 'nc'],
        'NZ' => ['nom' => 'New Zealand', 'flag' => 'nz'],
        'NI' => ['nom' => 'Nicaragua', 'flag' => 'ni'],
        'NE' => ['nom' => 'Niger', 'flag' => 'ne'],
        'NG' => ['nom' => 'Nigeria', 'flag' => 'ng'],
        'NU' => ['nom' => 'Niue', 'flag' => 'nu'],
        'NF' => ['nom' => 'Norfolk Island', 'flag' => 'nf'],
        'MP' => ['nom' => 'Northern Mariana Islands', 'flag' => 'mp'],
        'NO' => ['nom' => 'Norway', 'flag' => 'no'],
        'OM' => ['nom' => 'Oman', 'flag' => 'om'],
        'PK' => ['nom' => 'Pakistan', 'flag' => 'pk'],
        'PW' => ['nom' => 'Palau', 'flag' => 'pw'],
        'PS' => ['nom' => 'Palestine, State of', 'flag' => 'ps'],
        'PA' => ['nom' => 'Panama', 'flag' => 'pa'],
        'PG' => ['nom' => 'Papua New Guinea', 'flag' => 'pg'],
        'PY' => ['nom' => 'Paraguay', 'flag' => 'py'],
        'PE' => ['nom' => 'Peru', 'flag' => 'pe'],
        'PH' => ['nom' => 'Philippines', 'flag' => 'ph'],
        'PN' => ['nom' => 'Pitcairn', 'flag' => 'pn'],
        'PL' => ['nom' => 'Poland', 'flag' => 'pl'],
        'PT' => ['nom' => 'Portugal', 'flag' => 'pt'],
        'PR' => ['nom' => 'Puerto Rico', 'flag' => 'pr'],
        'QA' => ['nom' => 'Qatar', 'flag' => 'qa'],
        'RE' => ['nom' => 'Réunion', 'flag' => 're'],
        'RO' => ['nom' => 'Romania', 'flag' => 'ro'],
        'RU' => ['nom' => 'Russian Federation', 'flag' => 'ru'],
        'RW' => ['nom' => 'Rwanda', 'flag' => 'rw'],
        'BL' => ['nom' => 'Saint Barthélemy', 'flag' => 'bl'],
        'SH' => ['nom' => 'Saint Helena, Ascension and Tristan da Cunha', 'flag' => 'sh'],
        'KN' => ['nom' => 'Saint Kitts and Nevis', 'flag' => 'kn'],
        'LC' => ['nom' => 'Saint Lucia', 'flag' => 'lc'],
        'MF' => ['nom' => 'Saint Martin (French part)', 'flag' => 'mf'],
        'PM' => ['nom' => 'Saint Pierre and Miquelon', 'flag' => 'pm'],
        'VC' => ['nom' => 'Saint Vincent and the Grenadines', 'flag' => 'vc'],
        'WS' => ['nom' => 'Samoa', 'flag' => 'ws'],
        'SM' => ['nom' => 'San Marino', 'flag' => 'sm'],
        'ST' => ['nom' => 'Sao Tome and Principe', 'flag' => 'st'],
        'SA' => ['nom' => 'Saudi Arabia', 'flag' => 'sa'],
        'SN' => ['nom' => 'Senegal', 'flag' => 'sn'],
        'RS' => ['nom' => 'Serbia', 'flag' => 'rs'],
        'SC' => ['nom' => 'Seychelles', 'flag' => 'sc'],
        'SL' => ['nom' => 'Sierra Leone', 'flag' => 'sl'],
        'SG' => ['nom' => 'Singapore', 'flag' => 'sg'],
        'SX' => ['nom' => 'Sint Maarten (Dutch part)', 'flag' => 'sx'],
        'SK' => ['nom' => 'Slovakia', 'flag' => 'sk'],
        'SI' => ['nom' => 'Slovenia', 'flag' => 'si'],
        'SB' => ['nom' => 'Solomon Islands', 'flag' => 'sb'],
        'SO' => ['nom' => 'Somalia', 'flag' => 'so'],
        'ZA' => ['nom' => 'South Africa', 'flag' => 'za'],
        'GS' => ['nom' => 'South Georgia and the South Sandwich Islands', 'flag' => 'gs'],
        'SS' => ['nom' => 'South Sudan', 'flag' => 'ss'],
        'ES' => ['nom' => 'Spain', 'flag' => 'es'],
        'LK' => ['nom' => 'Sri Lanka', 'flag' => 'lk'],
        'SD' => ['nom' => 'Sudan', 'flag' => 'sd'],
        'SR' => ['nom' => 'Suriname', 'flag' => 'sr'],
        'SJ' => ['nom' => 'Svalbard and Jan Mayen', 'flag' => 'sj'],
        'SE' => ['nom' => 'Sweden', 'flag' => 'se'],
        'CH' => ['nom' => 'Switzerland', 'flag' => 'ch'],
        'SY' => ['nom' => 'Syrian Arab Republic', 'flag' => 'sy'],
        'TW' => ['nom' => 'Taiwan', 'flag' => 'tw'],
        'TJ' => ['nom' => 'Tajikistan', 'flag' => 'tj'],
        'TZ' => ['nom' => 'Tanzania', 'flag' => 'tz'],
        'TH' => ['nom' => 'Thailand', 'flag' => 'th'],
        'TL' => ['nom' => 'Timor-Leste', 'flag' => 'tl'],
        'TG' => ['nom' => 'Togo', 'flag' => 'tg'],
        'TK' => ['nom' => 'Tokelau', 'flag' => 'tk'],
        'TO' => ['nom' => 'Tonga', 'flag' => 'to'],
        'TT' => ['nom' => 'Trinidad and Tobago', 'flag' => 'tt'],
        'TN' => ['nom' => 'Tunisia', 'flag' => 'tn'],
        'TR' => ['nom' => 'Turkey', 'flag' => 'tr'],
        'TM' => ['nom' => 'Turkmenistan', 'flag' => 'tm'],
        'TC' => ['nom' => 'Turks and Caicos Islands', 'flag' => 'tc'],
        'TV' => ['nom' => 'Tuvalu', 'flag' => 'tv'],
        'UG' => ['nom' => 'Uganda', 'flag' => 'ug'],
        'UA' => ['nom' => 'Ukraine', 'flag' => 'ua'],
        'AE' => ['nom' => 'United Arab Emirates', 'flag' => 'ae'],
        'GB' => ['nom' => 'United Kingdom', 'flag' => 'gb'],
        'US' => ['nom' => 'United States', 'flag' => 'us'],
        'UM' => ['nom' => 'United States Minor Outlying Islands', 'flag' => 'um'],
        'UY' => ['nom' => 'Uruguay', 'flag' => 'uy'],
        'UZ' => ['nom' => 'Uzbekistan', 'flag' => 'uz'],
        'VU' => ['nom' => 'Vanuatu', 'flag' => 'vu'],
        'VE' => ['nom' => 'Venezuela', 'flag' => 've'],
        'VN' => ['nom' => 'Viet Nam', 'flag' => 'vn'],
        'VG' => ['nom' => 'Virgin Islands (British)', 'flag' => 'vg'],
        'VI' => ['nom' => 'Virgin Islands (U.S.)', 'flag' => 'vi'],
        'WF' => ['nom' => 'Wallis and Futuna', 'flag' => 'wf'],
        'EH' => ['nom' => 'Western Sahara', 'flag' => 'eh'],
        'YE' => ['nom' => 'Yemen', 'flag' => 'ye'],
        'ZM' => ['nom' => 'Zambia', 'flag' => 'zm'],
        'ZW' => ['nom' => 'Zimbabwe', 'flag' => 'zw'],
    ]
];